name: Build qtp-libass
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"

env:
  CFLAGS: -mmacosx-version-min=10.12
  LDFLAGS: -mmacosx-version-min=10.12

jobs:
  release-osx:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Install qtp-libass
        run: |
          brew tap xjbeta/homebrew-libass
          brew install qtp-libass

      - name: Run change_lib_dependencies.rb
        run: |
          mkdir deps
          other/change_lib_dependencies.rb "$(brew --prefix)" "$(brew --prefix qtp-libass)/lib/libass.dylib"

      - name: dylibs LC_BUILD_VERSION LC_VERSION_MIN_MACOSX
        shell: zsh {0}
        run: |
          for lib in deps/lib/*; do (echo $lib; otool -l $lib | grep -i LC_BUILD_VERSION -A 4); done
          for lib in deps/lib/*; do (echo $lib; otool -l $lib | grep -A 3 LC_VERSION_MIN_MACOSX); done
        
        

      - name: Archive libs
        uses: actions/upload-artifact@v2
        with:
          name: deps
          path: deps/
          
